apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: online-course
spec:
  replicas: 3
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
        - name: course-service
          image: course_service:latest
          imagePullPolicy: Never
          env:
            - name: DATABASE_SYNC_URL
              value: "postgresql+psycopg://postgres:postgres@course-db:5432/course"
            - name: APP_PORT
              value: "8000"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  # имя под которым будет видеть nginx
  name: course-api
  namespace: online-course
spec:
  selector:
    app: course-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
