apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-db-pvc
  namespace: online-course
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: course-db
  namespace: online-course
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: course-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-db
  namespace: online-course
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-db
  template:
    metadata:
      labels:
        app: course-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: course
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: course-db-pvc
