"""create modules and tasks

Revision ID: 5048e99f2987
Revises: 95da4a819640
Create Date: 2025-10-18 03:54:51.579871
"""

from alembic import op
import sqlalchemy as sa

revision = '5048e99f2987'
down_revision = '95da4a819640'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
