"""create modules and tasks

Revision ID: 95da4a819640
Revises: 
Create Date: 2025-10-18 03:52:56.694931
"""

from alembic import op
import sqlalchemy as sa

revision = '95da4a819640'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
